name: "MODEL_TASK"
backend: "python"

input [
  {
    name: "encoder_input_ids"
    data_type: TYPE_INT64
    dims: [ TOKEN_INPUT_DIM ]
  },
  {
    name: "encoder_attention_mask"
    data_type: TYPE_INT64
    dims: [ TOKEN_INPUT_DIM ]
  },
  {
    name: "batch_mask"
    data_type: TYPE_BOOL
    dims: [ NUM_ENSEMBLE, -1 ]
  }
]

parameters: { key: "FORCE_CPU_ONLY_INPUT_TENSORS" value: {string_value:"no"}}

output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [ SCORE_OUTPUT_DIM ]
  },
  {
    name: "batch_mask"
    data_type: TYPE_BOOL
    dims: [ NUM_ENSEMBLE, -1 ]
  }
]

instance_group [
  {
    count: NUM_REPLICA
    kind: KIND_GPU
    gpus: [ DEVICE_MAP ]
  }
]