name: "t5_sst2_ensemble"
platform: "ensemble"

input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1, 128 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1, 128 ]
  },
  {
    name: "ensemble_outputs"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  },
  {
    name: "batch_mask"
    data_type: TYPE_BOOL
    dims: [ 4, -1 ]
  }
]

output [
  {
    name: "outputs"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  },
  {
    name: "batch_mask"
    data_type: TYPE_BOOL
    dims: [ 4, -1 ]
  }
]

ensemble_scheduling {
  step [ 
    {
      model_name: "t5-small-lm-adapt_sst2"
      model_version: -1
      input_map {
        key: "input_ids"
        value: "input_ids"
      }
      input_map {
        key: "attention_mask"
        value: "attention_mask"
      }
      input_map {
        key: "batch_mask"
        value: "batch_mask"
      }
      input_map {
        key: "ensemble_outputs"
        value: "ensemble_outputs"
      }
      output_map {
        key: "outputs"
        value: "ensemble_0"
      }
      output_map {
        key: "batch_mask"
        value: "mask_0"
      }
    },
    {
      model_name: "t5-base-lm-adapt_sst2"
      model_version: -1
      input_map {
        key: "ensemble_outputs"
        value: "ensemble_0"
      }
      input_map {
        key: "batch_mask"
        value: "mask_0"
      }
      input_map {
        key: "input_ids"
        value: "input_ids"
      }
      input_map {
        key: "attention_mask"
        value: "attention_mask"
      }
      output_map {
        key: "outputs"
        value: "ensemble_1"
      }
      output_map {
        key: "batch_mask"
        value: "mask_1"
      }
    },
    {
      model_name: "t5-large-lm-adapt_sst2"
      model_version: -1
      input_map {
        key: "ensemble_outputs"
        value: "ensemble_1"
      }
      input_map {
        key: "batch_mask"
        value: "mask_1"
      }
      input_map {
        key: "input_ids"
        value: "input_ids"
      }
      input_map {
        key: "attention_mask"
        value: "attention_mask"
      }
      output_map {
        key: "outputs"
        value: "ensemble_2"
      }
      output_map {
        key: "batch_mask"
        value: "mask_2"
      }
    },
    {
      model_name: "t5-xl-lm-adapt_sst2"
      model_version: -1
      input_map {
        key: "ensemble_outputs"
        value: "ensemble_2"
      }
      input_map {
        key: "batch_mask"
        value: "mask_2"
      }
      input_map {
        key: "input_ids"
        value: "input_ids"
      }
      input_map {
        key: "attention_mask"
        value: "attention_mask"
      }
      output_map {
        key: "outputs"
        value: "outputs"
      }
      output_map {
        key: "batch_mask"
        value: "batch_mask"
      }
    }
  ]
}